# Generated by Django 6.0.1 on 2026-02-08 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_appointment_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorProfile',
            new_name='Doctor',
        ),
        migrations.RenameField(
            model_name='emergencyalert',
            old_name='contact_number',
            new_name='patient_phone',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='emergency_type',
        ),
        migrations.RemoveField(
            model_name='emergencyalert',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='emergencyalert',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='message',
            field=models.TextField(),
        ),
    ]
