# Generated by Django 6.0.1 on 2026-02-06 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_available_doctor_experience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio',
        ),
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
