# Generated by Django 6.0.1 on 2026-02-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_alter_appointment_patient_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
