# Generated by Django 6.0.1 on 2026-02-09 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed')], default='waiting', max_length=20),
        ),
    ]
