# Generated by Django 6.0.1 on 2026-03-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'queue_number']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='queue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
