# Generated by Django 6.0.1 on 2026-03-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0013_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='disease',
            field=models.CharField(default='Not Specified', max_length=200),
        ),
    ]
